export const DINOSAUR_LIST = [
  { name: "Abelichnus", diet: null, type: null, length_m: null, max_ma: 99.6, min_ma: 93.5, region: "Neuquén", class: "Saurischia", family: null },
  { name: "Abrosaurus", diet: null, type: null, length_m: null, max_ma: 170.3, min_ma: 163.5, region: "Sichuan", class: "Saurischia", family: null },
  { name: "Acristavus", diet: null, type: null, length_m: null, max_ma: 83.5, min_ma: 70.6, region: "Montana", class: "Ornithischia", family: "Hadrosauridae" },
  { name: "Acrotholus", diet: null, type: null, length_m: null, max_ma: 85.8, min_ma: 83.5, region: "Alberta", class: "Ornithischia", family: "Pachycephalosauridae" },
  { name: "Allosaurus", diet: "carnivorous", type: "large theropod", length_m: 12.0, max_ma: 157.3, min_ma: 145.0, region: "Wyoming", class: "Saurischia", family: "Allosauridae" },
  { name: "Alnashetri", diet: null, type: null, length_m: null, max_ma: 99.6, min_ma: 93.5, region: "Río Negro", class: "Saurischia", family: "Alvarezsauridae" },
  { name: "Altirhinus", diet: null, type: null, length_m: null, max_ma: 109.0, min_ma: 99.6, region: "Dornogov", class: "Ornithischia", family: null },
  { name: "Alwalkeria", diet: null, type: null, length_m: null, max_ma: 237.0, min_ma: 208.5, region: "Andhra Pradesh", class: "Saurischia", family: null },
  { name: "Alxasaurus", diet: null, type: null, length_m: null, max_ma: 125.0, min_ma: 113.0, region: "Nei Mongol", class: "Saurischia", family: null },
  { name: "Ammosaurus", diet: "herbivorous", type: "sauropod", length_m: 5.0, max_ma: 201.3, min_ma: 196.5, region: "Nova Scotia", class: "Saurischia", family: "Anchisauridae" },
  { name: "Amtosaurus", diet: null, type: null, length_m: null, max_ma: 100.5, min_ma: 89.8, region: "Omnogov", class: "Ornithischia", family: null },
  { name: "Anabisetia", diet: null, type: null, length_m: null, max_ma: 93.5, min_ma: 89.3, region: "Neuquén", class: "Ornithischia", family: null },
  { name: "Anatotitan", diet: null, type: null, length_m: null, max_ma: 72.1, min_ma: 66.0, region: "South Dakota", class: "Ornithischia", family: "Hadrosauridae" },
  { name: "Anchiornis", diet: null, type: null, length_m: null, max_ma: 163.5, min_ma: 157.3, region: "Liaoning", class: "Saurischia", family: null },
  { name: "Andesaurus", diet: null, type: null, length_m: null, max_ma: 99.6, min_ma: 93.5, region: "Neuquén", class: "Saurischia", family: null },
  { name: "Angaturama", diet: null, type: null, length_m: null, max_ma: 113.0, min_ma: 100.5, region: "Ceará", class: "Saurischia", family: "Spinosauridae" },
  { name: "Animantarx", diet: null, type: null, length_m: null, max_ma: 105.3, min_ma: 99.6, region: "Utah", class: "Ornithischia", family: "Nodosauridae" },
  { name: "Aoniraptor", diet: null, type: null, length_m: null, max_ma: 99.6, min_ma: 89.3, region: "Río Negro", class: "Saurischia", family: "Neovenatoridae" },
  { name: "Apatichnus", diet: null, type: null, length_m: null, max_ma: 201.3, min_ma: 190.8, region: "Massachusetts", class: "Ornithischia", family: "Anomoepodidae" },
  { name: "Arcusaurus", diet: null, type: null, length_m: null, max_ma: 201.3, min_ma: 190.8, region: "Free State", class: "Saurischia", family: null },
  { name: "Atlasaurus", diet: null, type: null, length_m: null, max_ma: 168.3, min_ma: 166.1, region: "Azilal", class: "Saurischia", family: null },
  { name: "Aucasaurus", diet: "carnivorous", type: "large theropod", length_m: 5.0, max_ma: 83.5, min_ma: 70.6, region: "Neuquén", class: "Saurischia", family: "Abelisauridae" },
  { name: "Bagaraatan", diet: null, type: null, length_m: null, max_ma: 83.6, min_ma: 66.0, region: "Omnogov", class: "Saurischia", family: null },
  { name: "Barosaurus", diet: "herbivorous", type: "sauropod", length_m: 24.0, max_ma: 155.7, min_ma: 145.0, region: "Wyoming", class: "Saurischia", family: "Diplodocidae" },
  { name: "Barsboldia", diet: null, type: null, length_m: null, max_ma: 83.6, min_ma: 66.0, region: "Omnogov", class: "Ornithischia", family: "Hadrosauridae" },
  { name: "Baurutitan", diet: null, type: null, length_m: null, max_ma: 72.1, min_ma: 66.0, region: "Minas Gerais", class: "Saurischia", family: "Titanosauridae" },
  { name: "Boreonykus", diet: null, type: null, length_m: null, max_ma: 83.5, min_ma: 70.6, region: "Alberta", class: "Saurischia", family: "Dromaeosauridae" },
  { name: "Cedarpelta", diet: "herbivorous", type: "armored dinosaur", length_m: 10.0, max_ma: 125.0, min_ma: 100.5, region: "Utah", class: "Ornithischia", family: "Ankylosauridae" },
  { name: "Cerasinops", diet: null, type: null, length_m: null, max_ma: 83.6, min_ma: 72.1, region: "Montana", class: "Ornithischia", family: "Leptoceratopsidae" },
  { name: "Chebsaurus", diet: null, type: null, length_m: null, max_ma: 174.1, min_ma: 163.5, region: "Naama", class: "Saurischia", family: "Cetiosauridae" },
  { name: "Claosaurus", diet: null, type: null, length_m: null, max_ma: 89.3, min_ma: 70.6, region: "Kansas", class: "Ornithischia", family: null },
  { name: "Dahalokely", diet: null, type: null, length_m: null, max_ma: 93.9, min_ma: 89.8, region: null, class: "Saurischia", family: "Abelisauridae" },
  { name: "Datanglong", diet: null, type: null, length_m: null, max_ma: 125.0, min_ma: 113.0, region: "Guangxi Zhuang", class: "Saurischia", family: null },
  { name: "Datonglong", diet: null, type: null, length_m: null, max_ma: 100.5, min_ma: 72.1, region: "Shanxi", class: "Ornithischia", family: null },
  { name: "Daxiatitan", diet: null, type: null, length_m: null, max_ma: 145.0, min_ma: 100.5, region: "Gansu", class: "Saurischia", family: null },
  { name: "Diplodocus", diet: "herbivorous", type: "sauropod", length_m: 26.0, max_ma: 157.3, min_ma: 145.0, region: "Wyoming", class: "Saurischia", family: "Diplodocidae" },
  { name: "Dracopelta", diet: null, type: null, length_m: null, max_ma: 150.8, min_ma: 145.0, region: "Lisboa", class: "Ornithischia", family: null },
  { name: "Dryosaurus", diet: "herbivorous", type: "ornithopod", length_m: 4.0, max_ma: 157.3, min_ma: 145.0, region: "Utah", class: "Ornithischia", family: "Dryosauridae" },
  { name: "Duriatitan", diet: null, type: null, length_m: null, max_ma: 155.7, min_ma: 150.8, region: "England", class: "Saurischia", family: null },
  { name: "Edmontonia", diet: "herbivorous", type: "armored dinosaur", length_m: 4.0, max_ma: 83.6, min_ma: 72.1, region: "Montana", class: "Ornithischia", family: "Nodosauridae" },
  { name: "Elmisaurus", diet: null, type: null, length_m: null, max_ma: 83.6, min_ma: 66.0, region: "Omnogov", class: "Saurischia", family: "Caenagnathidae" },
  { name: "Emausaurus", diet: "herbivorous", type: "armored dinosaur", length_m: 2.0, max_ma: 183.0, min_ma: 182.0, region: "Mecklenburg-Vorpommern", class: "Ornithischia", family: null },
  { name: "Eodromaeus", diet: null, type: null, length_m: null, max_ma: 237.0, min_ma: 228.0, region: "San Juan", class: "Saurischia", family: null },
  { name: "Eosauropus", diet: null, type: null, length_m: null, max_ma: 228.0, min_ma: 208.5, region: "Wales", class: "Saurischia", family: null },
  { name: "Eotyrannus", diet: "carnivorous", type: "large theropod", length_m: 5.0, max_ma: 136.4, min_ma: 125.45, region: "England", class: "Saurischia", family: null },
  { name: "Fruitadens", diet: null, type: null, length_m: null, max_ma: 150.8, min_ma: 145.0, region: "Colorado", class: "Ornithischia", family: "Heterodontosauridae" },
  { name: "Fukuititan", diet: null, type: null, length_m: null, max_ma: 129.4, min_ma: 125.0, region: "Fukui", class: "Saurischia", family: null },
  { name: "Galeamopus", diet: null, type: null, length_m: null, max_ma: 157.3, min_ma: 145.0, region: "Wyoming", class: "Saurischia", family: "Diplodocidae" },
  { name: "Gallimimus", diet: "omnivorous", type: "large theropod", length_m: 6.0, max_ma: 83.6, min_ma: 66.0, region: "Omnogov", class: "Saurischia", family: "Ornithomimidae" },
  { name: "Gasosaurus", diet: "carnivorous", type: "small theropod", length_m: 4.0, max_ma: 170.3, min_ma: 163.5, region: "Sichuan", class: "Saurischia", family: null },
  { name: "Genusaurus", diet: null, type: null, length_m: null, max_ma: 109.0, min_ma: 105.3, region: "Provence-Alpes-Côte-d'Azur", class: "Saurischia", family: "Abelisauridae" },
  { name: "Gobisaurus", diet: "herbivorous", type: "armored dinosaur", length_m: 5.0, max_ma: 93.9, min_ma: 89.8, region: "Nei Mongol", class: "Ornithischia", family: "Ankylosauridae" },
  { name: "Gregaripus", diet: null, type: null, length_m: null, max_ma: 228.0, min_ma: 208.5, region: "Virginia", class: "Ornithischia", family: null },
  { name: "Hanssuesia", diet: null, type: null, length_m: null, max_ma: 83.6, min_ma: 72.1, region: "Alberta", class: "Ornithischia", family: "Pachycephalosauridae" },
  { name: "Harpymimus", diet: "omnivorous", type: "small theropod", length_m: 2.0, max_ma: 109.0, min_ma: 99.6, region: "Dornogov", class: "Saurischia", family: null },
  { name: "Hippodraco", diet: null, type: null, length_m: null, max_ma: 130.0, min_ma: 122.46, region: "Utah", class: "Ornithischia", family: null },
  { name: "Hopiichnus", diet: null, type: null, length_m: null, max_ma: 199.3, min_ma: 182.7, region: "Arizona", class: "Saurischia", family: "Ornithomimidae" },
  { name: "Ignotornis", diet: null, type: null, length_m: null, max_ma: 125.0, min_ma: 100.5, region: "Gyeongsangnam-do", class: "Saurischia", family: null },
  { name: "Ilokelesia", diet: null, type: null, length_m: null, max_ma: 99.6, min_ma: 89.8, region: "Neuquén", class: "Saurischia", family: "Abelisauridae" },
  { name: "Indosaurus", diet: null, type: null, length_m: null, max_ma: 72.1, min_ma: 66.0, region: "Madhya Pradesh", class: "Saurischia", family: "Abelisauridae" },
  { name: "Indosuchus", diet: "carnivorous", type: "large theropod", length_m: 7.0, max_ma: 72.1, min_ma: 66.0, region: "Madhya Pradesh", class: "Saurischia", family: "Abelisauridae" },
  { name: "Janenschia", diet: "herbivorous", type: "sauropod", length_m: 20.0, max_ma: 152.1, min_ma: 145.0, region: "Lindi", class: "Saurischia", family: null },
  { name: "Jialingpus", diet: null, type: null, length_m: null, max_ma: 163.5, min_ma: 145.0, region: "Sichuan", class: "Saurischia", family: null },
  { name: "Juratyrant", diet: null, type: null, length_m: null, max_ma: 150.8, min_ma: 145.0, region: "England", class: "Saurischia", family: null },
  { name: "Kaatedocus", diet: null, type: null, length_m: null, max_ma: 157.3, min_ma: 152.1, region: "Wyoming", class: "Saurischia", family: "Diplodocidae" },
  { name: "Kotasaurus", diet: "herbivorous", type: "sauropod", length_m: 9.0, max_ma: 199.3, min_ma: 182.7, region: "Andhra Pradesh", class: "Saurischia", family: null },
  { name: "Latirhinus", diet: null, type: null, length_m: null, max_ma: 83.5, min_ma: 70.6, region: "Coahuila", class: "Ornithischia", family: "Hadrosauridae" },
  { name: "Levnesovia", diet: null, type: null, length_m: null, max_ma: 93.5, min_ma: 89.3, region: "Navoi", class: "Ornithischia", family: null },
  { name: "Leyesaurus", diet: null, type: null, length_m: null, max_ma: 201.3, min_ma: 174.1, region: "San Juan", class: "Saurischia", family: "Massospondylidae" },
  { name: "Ligabueino", diet: null, type: null, length_m: null, max_ma: 129.4, min_ma: 122.46, region: "Neuquén", class: "Saurischia", family: "Noasauridae" },
  { name: "Limusaurus", diet: null, type: null, length_m: null, max_ma: 163.5, min_ma: 157.3, region: "Xinjiang", class: "Saurischia", family: null },
  { name: "Linhenykus", diet: null, type: null, length_m: null, max_ma: 83.6, min_ma: 72.1, region: "Nei Mongol", class: "Saurischia", family: null },
  { name: "Lufengopus", diet: null, type: null, length_m: null, max_ma: 174.1, min_ma: 163.5, region: "Yunnan", class: "Saurischia", family: "Eubrontidae" },
  { name: "Luluichnus", diet: null, type: null, length_m: null, max_ma: 139.8, min_ma: 125.0, region: "Western Australia", class: "Ornithischia", family: null },
  { name: "Luoyanggia", diet: null, type: null, length_m: null, max_ma: 100.5, min_ma: 89.8, region: "Henan", class: "Saurischia", family: "Oviraptoridae" },
  { name: "Lycorhinus", diet: "herbivorous", type: "ornithopod", length_m: 1.2, max_ma: 201.3, min_ma: 190.8, region: "Free State", class: "Ornithischia", family: "Heterodontosauridae" },
  { name: "Mapusaurus", diet: "carnivorous", type: "large theropod", length_m: 13.0, max_ma: 99.6, min_ma: 89.8, region: "Neuquén", class: "Saurischia", family: "Carcharodontosauridae" },
  { name: "Marisaurus", diet: null, type: null, length_m: null, max_ma: 72.1, min_ma: 66.0, region: "Balochistan", class: "Saurischia", family: "Balochisauridae" },
  { name: "Megaraptor", diet: null, type: null, length_m: null, max_ma: 93.5, min_ma: 85.8, region: "Neuquén", class: "Saurischia", family: "Megaraptoridae" },
  { name: "Meroktenos", diet: null, type: null, length_m: null, max_ma: 237.0, min_ma: 201.3, region: "Mafeteng", class: "Saurischia", family: null },
  { name: "Nanosaurus", diet: null, type: null, length_m: null, max_ma: 157.3, min_ma: 145.0, region: "Colorado", class: "Ornithischia", family: null },
  { name: "Neovenator", diet: "carnivorous", type: "large theropod", length_m: 7.4, max_ma: 129.4, min_ma: 125.0, region: "England", class: "Saurischia", family: "Neovenatoridae" },
  { name: "Nodosaurus", diet: "herbivorous", type: "armored dinosaur", length_m: 5.0, max_ma: 83.5, min_ma: 70.6, region: "Alberta", class: "Ornithischia", family: "Nodosauridae" },
  { name: "Olorotitan", diet: null, type: null, length_m: null, max_ma: 70.6, min_ma: 66.0, region: "Amur", class: "Ornithischia", family: "Hadrosauridae" },
  { name: "Omeisaurus", diet: "herbivorous", type: "sauropod", length_m: 20.0, max_ma: 174.1, min_ma: 163.5, region: "Sichuan", class: "Saurischia", family: null },
  { name: "Oohkotokia", diet: null, type: null, length_m: null, max_ma: 83.5, min_ma: 70.6, region: "Montana", class: "Ornithischia", family: "Ankylosauridae" },
  { name: "Orkoraptor", diet: null, type: null, length_m: null, max_ma: 70.6, min_ma: 66.0, region: "Santa Cruz", class: "Saurischia", family: "Megaraptoridae" },
  { name: "Orodromeus", diet: "herbivorous", type: "ornithopod", length_m: 2.0, max_ma: 83.6, min_ma: 72.1, region: "Montana", class: "Ornithischia", family: "Thescelosauridae" },
  { name: "Pakisaurus", diet: null, type: null, length_m: null, max_ma: 72.1, min_ma: 66.0, region: "Balochistan", class: "Saurischia", family: "Pakisauridae" },
  { name: "Pantydraco", diet: "herbivorous", type: "ornithopod", length_m: 3.0, max_ma: 208.5, min_ma: 201.3, region: "Wales", class: "Saurischia", family: null },
  { name: "Pectinodon", diet: null, type: null, length_m: null, max_ma: 70.6, min_ma: 66.0, region: "Wyoming", class: "Saurischia", family: "Troodontidae" },
  { name: "Pegomastax", diet: null, type: null, length_m: null, max_ma: 201.3, min_ma: 190.8, region: "Free State", class: "Ornithischia", family: "Heterodontosauridae" },
  { name: "Plectropus", diet: null, type: null, length_m: null, max_ma: 201.3, min_ma: 190.8, region: "Connecticut", class: "Saurischia", family: null },
  { name: "Plesiornis", diet: null, type: null, length_m: null, max_ma: 201.3, min_ma: 199.3, region: "Massachusetts", class: "Saurischia", family: null },
  { name: "Pyroraptor", diet: null, type: null, length_m: null, max_ma: 83.5, min_ma: 66.0, region: "Cataluña", class: "Saurischia", family: "Dromaeosauridae" },
  { name: "Rajasaurus", diet: null, type: null, length_m: null, max_ma: 72.1, min_ma: 66.0, region: "Gujarat", class: "Saurischia", family: "Abelisauridae" },
  { name: "Rocasaurus", diet: null, type: null, length_m: null, max_ma: 83.5, min_ma: 66.0, region: "Río Negro", class: "Saurischia", family: "Saltasauridae" },
  { name: "Rukwatitan", diet: null, type: null, length_m: null, max_ma: 125.0, min_ma: 93.9, region: null, class: "Saurischia", family: null },
  { name: "Saturnalia", diet: null, type: null, length_m: null, max_ma: 237.0, min_ma: 208.5, region: "Rio Grande do Sul", class: "Saurischia", family: null },
  { name: "Sauroniops", diet: null, type: null, length_m: null, max_ma: 100.5, min_ma: 93.9, region: "Meknès-Tafilalet", class: "Saurischia", family: "Carcharodontosauridae" },
  { name: "Sauropelta", diet: "herbivorous", type: "armored dinosaur", length_m: 6.5, max_ma: 125.0, min_ma: 109.0, region: "Utah", class: "Ornithischia", family: "Nodosauridae" },
  { name: "Segisaurus", diet: "carnivorous", type: "small theropod", length_m: 1.5, max_ma: 190.8, min_ma: 174.1, region: "Arizona", class: "Saurischia", family: null },
  { name: "Shixinggia", diet: null, type: null, length_m: null, max_ma: 72.1, min_ma: 66.0, region: "Guangdong", class: "Saurischia", family: "Oviraptoridae" },
  { name: "Siamopodus", diet: null, type: null, length_m: null, max_ma: 145.0, min_ma: 125.0, region: null, class: "Saurischia", family: null },
  { name: "Sinosaurus", diet: null, type: null, length_m: null, max_ma: 201.3, min_ma: 199.3, region: "Yunnan", class: "Saurischia", family: null },
  { name: "Sphingopus", diet: null, type: null, length_m: null, max_ma: 247.2, min_ma: 237.0, region: "Saône-et-Loire", class: "Saurischia", family: "Parachirotheriidae" },
  { name: "Spiclypeus", diet: null, type: null, length_m: null, max_ma: 83.5, min_ma: 70.6, region: "Montana", class: "Ornithischia", family: "Ceratopsidae" },
  { name: "Stegoceras", diet: "herbivorous", type: "ornithopod", length_m: 2.4, max_ma: 83.5, min_ma: 70.6, region: "Montana", class: "Ornithischia", family: "Pachycephalosauridae" },
  { name: "Stegopelta", diet: null, type: null, length_m: null, max_ma: 105.3, min_ma: 93.5, region: "Wyoming", class: "Ornithischia", family: null },
  { name: "Stegopodus", diet: null, type: null, length_m: null, max_ma: 161.2, min_ma: 152.1, region: "Utah", class: "Ornithischia", family: null },
  { name: "Stenopelix", diet: "herbivorous", type: "ceratopsian", length_m: 1.5, max_ma: 145.0, min_ma: 139.8, region: "Niedersachsen", class: "Ornithischia", family: null },
  { name: "Suchomimus", diet: "carnivorous", type: "large theropod", length_m: 11.0, max_ma: 125.0, min_ma: 100.5, region: null, class: "Saurischia", family: "Spinosauridae" },
  { name: "Talenkauen", diet: null, type: null, length_m: null, max_ma: 70.6, min_ma: 66.0, region: "Santa Cruz", class: "Ornithischia", family: null },
  { name: "Tataouinea", diet: null, type: null, length_m: null, max_ma: 112.03, min_ma: 109.0, region: "Tataouine", class: "Saurischia", family: "Rebbachisauridae" },
  { name: "Tendaguria", diet: null, type: null, length_m: null, max_ma: 152.1, min_ma: 145.0, region: "Lindi", class: "Saurischia", family: null },
  { name: "Tianyulong", diet: null, type: null, length_m: null, max_ma: 167.7, min_ma: 150.8, region: "Liaoning", class: "Ornithischia", family: "Heterodontosauridae" },
  { name: "Torosaurus", diet: "herbivorous", type: "ceratopsian", length_m: 7.5, max_ma: 72.1, min_ma: 66.0, region: "North Dakota", class: "Ornithischia", family: "Ceratopsidae" },
  { name: "Trinisaura", diet: null, type: null, length_m: null, max_ma: 83.5, min_ma: 70.6, region: null, class: "Ornithischia", family: null },
  { name: "Ugrunaaluk", diet: null, type: null, length_m: null, max_ma: 70.6, min_ma: 66.0, region: "Alaska", class: "Ornithischia", family: "Hadrosauridae" },
  { name: "Unaysaurus", diet: null, type: null, length_m: null, max_ma: 228.0, min_ma: 208.5, region: "Rio Grande do Sul", class: "Saurischia", family: "Plateosauridae" },
  { name: "Utahraptor", diet: "carnivorous", type: "large theropod", length_m: 6.0, max_ma: 129.4, min_ma: 125.0, region: "Utah", class: "Saurischia", family: "Dromaeosauridae" },
  { name: "Variraptor", diet: null, type: null, length_m: null, max_ma: 83.5, min_ma: 70.6, region: "Provence-Alpes-Côte d'Azur", class: "Saurischia", family: "Dromaeosauridae" },
  { name: "Viavenator", diet: null, type: null, length_m: null, max_ma: 86.3, min_ma: 83.6, region: "Neuquén", class: "Saurischia", family: "Abelisauridae" },
  { name: "Vulcanodon", diet: "herbivorous", type: "sauropod", length_m: 6.5, max_ma: 201.3, min_ma: 199.3, region: "Mashonaland North", class: "Saurischia", family: null },
  { name: "Wulatelong", diet: null, type: null, length_m: null, max_ma: 83.6, min_ma: 72.1, region: "Linhe", class: "Saurischia", family: "Oviraptoridae" },
  { name: "Xiangxipus", diet: null, type: null, length_m: null, max_ma: 100.5, min_ma: 66.0, region: "Hunan", class: "Saurischia", family: null },
  { name: "Xiaosaurus", diet: null, type: null, length_m: null, max_ma: 170.3, min_ma: 163.5, region: "Sichuan", class: "Ornithischia", family: null },
  { name: "Xiaotingia", diet: null, type: null, length_m: null, max_ma: 167.7, min_ma: 150.8, region: "Liaoning", class: "Saurischia", family: null },
  { name: "Xiuningpus", diet: null, type: null, length_m: null, max_ma: 100.5, min_ma: 66.0, region: "Anhui", class: "Saurischia", family: null },
  { name: "Xixianykus", diet: null, type: null, length_m: null, max_ma: 89.3, min_ma: 83.6, region: "Henan", class: "Saurischia", family: null },
  { name: "Yangtzepus", diet: null, type: null, length_m: null, max_ma: 125.0, min_ma: 89.8, region: "Sichuan", class: "Saurischia", family: null },
  { name: "Yezosaurus", diet: null, type: null, length_m: null, max_ma: 85.8, min_ma: 83.5, region: "Hokkaido", class: "Saurischia", family: "Tyrannosauridae" },
  { name: "Yueosaurus", diet: null, type: null, length_m: null, max_ma: 113.0, min_ma: 93.9, region: "Zhejiang", class: "Ornithischia", family: null },
  { name: "Yutyrannus", diet: null, type: null, length_m: null, max_ma: 129.4, min_ma: 113.0, region: "Liaoning", class: "Saurischia", family: "Proceratosauridae" },
  { name: "Zhongornis", diet: null, type: null, length_m: null, max_ma: 125.45, min_ma: 122.46, region: "Liaoning", class: "Saurischia", family: null }
];
